import type { ClientEvents } from 'discord.js'
import type { PluginComponentData } from '../registries/components.js'
import type { CronsConfigurations } from '../controllers/Crons.js'
import type { ConfigOptions } from '../controllers/Config.js'
import type { PluginDiscordEventData } from '../registries/events.js'
import type { PluginSlashCommandData } from '../registries/slashCommands.js'

/**
 * A database dependency on another plugin.
 * Captured at build time via `useDatabase('plugin-name')` calls and stored
 * in `package.json` under `fragment.dependencies`.
 */
export type PluginDependency = {
  /** Plugin key (metadata.name with "plugin-" prefix stripped) */
  name: string
  /** Exact version of the dependency captured at build time */
  version: string
}

export type PluginMetadata = {
  name: string
  version: string
  description: string
  author: string | { name: string; email: string }
  license: string
  /**
   * Semver range of the framework version this plugin requires.
   * Example: "^1.0.0"
   */
  frameworkVersion: string
  /**
   * Database dependencies on other plugins, auto-generated by the build system.
   * Core validates these at load time using semver diff rules:
   *   - patch diff → silent (fully compatible)
   *   - minor diff → warning
   *   - major diff → error (breaking change risk)
   */
  dependencies?: PluginDependency[]
}

/**
 * Context object passed to every plugin's setup() function.
 * All core capabilities are accessed through this interface —
 * plugin files must not create their own Discord connections.
 *
 * Database access: register your TypeORM entity classes via `registerEntity()`
 * and use their static methods (find, save, etc.) directly — they are backed
 * by core's DataSource which is re-initialised after setup() completes.
 */
export interface PluginContext {
  /** Unique identifier assigned to this plugin instance by core */
  readonly id: string
  readonly metadata: PluginMetadata

  /** Register a slash command or context-menu command (legacy registry; prefer `createCommand` from `discord`) */
  command<D extends boolean>(data: PluginSlashCommandData<D>): void
  /** Register a Discord event listener (legacy registry; prefer `createEvent` from `discord`) */
  event<K extends keyof ClientEvents>(data: PluginDiscordEventData<K>): void
  /** Register an interaction component handler (legacy registry; prefer `createResponder` from `discord`) */
  component(data: PluginComponentData): void
  /** Register a /config subcommand */
  config(data: ConfigOptions): void
  /** Register a cron job */
  cron<M>(data: CronsConfigurations<M>): void

  /** Register a TypeORM entity class — triggers DataSource re-initialisation after setup() */
  // eslint-disable-next-line @typescript-eslint/no-unsafe-function-type
  registerEntity(entity: Function): void

  /**
   * Register this plugin's entity schema in the global database registry so that
   * any other plugin (or core) can query its tables via `useDatabase(pluginName)`.
   *
   * The plugin name used as key is taken from `metadata.name` automatically.
   *
   * @example
   * // plugins/my-plugin/src/app.ts
   * import { schema } from '@/database'
   *
   * export async function setup(ctx: PluginContext) {
   *   ctx.registerSchema(schema)
   *   await registerAll(ctx)
   * }
   */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  registerSchema(schema: Record<string, any>): void
}

/**
 * Contract that every plugin module must satisfy.
 * Plugins are loaded via dynamic import(); this is what core expects to find.
 */
export interface PluginModule {
  /** Plugin metadata validated by core before setup() is called */
  metadata: PluginMetadata
  /** Called once by core to register commands, events, components, etc. */
  setup(ctx: PluginContext): Promise<void>
}
