import type {
  ClientEventKey,
  EventData,
  ResponderData,
  ResponderType,
} from '@ashu11a/constatic'
import type { CacheType } from 'discord.js'
import type { CronsConfigurations } from '../controllers/Crons.js'

/**
 * A database dependency on another plugin.
 * Captured at build time via `useDatabase('plugin-name')` calls and stored
 * in `package.json` under `fragment.dependencies`.
 */
export type PluginDependency = {
  /** Plugin key (metadata.name with "plugin-" prefix stripped) */
  name: string
  /** Exact version of the dependency captured at build time */
  version: string
}

export type PluginMetadata = {
  name: string
  version: string
  description: string
  author: string | { name: string; email: string }
  license: string
  /**
   * Semver range of the framework version this plugin requires.
   * Example: "^1.0.0"
   */
  frameworkVersion: string
  /**
   * Database dependencies on other plugins, auto-generated by the build system.
   * Core validates these at load time using semver diff rules:
   *   - patch diff → silent (fully compatible)
   *   - minor diff → warning
   *   - major diff → error (breaking change risk)
   */
  dependencies?: PluginDependency[]
}

/**
 * Context object passed to every plugin's setup() function.
 * All core capabilities are accessed through this interface —
 * plugin files must not create their own Discord connections.
 *
 * Database access: register your TypeORM entity classes via `registerEntity()`
 * and use their static methods (find, save, etc.) directly — they are backed
 * by core's DataSource which is re-initialised after setup() completes.
 */
export interface PluginContext {
  /** Unique identifier assigned to this plugin instance by core */
  readonly id: string
  readonly metadata: PluginMetadata

  /**
   * Instância de `Command` (export do módulo, após a cadeia `.action(…, bot)`)
   * ou, em raros casos, o objeto `CommandData` plano.
   */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  command: (data: any) => void
  event<K extends ClientEventKey>(data: EventData<K>): void
  component<Path extends string, Types extends readonly ResponderType[], Cache extends CacheType>(data: ResponderData<Path, Types, Cache>): void
  /** Register a cron job */
  cron<M>(data: CronsConfigurations<M>): void

  /** Register a TypeORM entity class — triggers DataSource re-initialisation after setup() */
  // eslint-disable-next-line @typescript-eslint/no-unsafe-function-type
  registerEntity(entity: Function): void

  /**
   * Register this plugin's entity schema in the global database registry so that
   * any other plugin (or core) can query its tables via `useDatabase(pluginName)`.
   *
   * The plugin name used as key is taken from `metadata.name` automatically.
   *
   * @example
   * // plugins/my-plugin/src/app.ts
   * import { schema } from '@/database'
   *
   * export async function setup(ctx: PluginContext) {
   *   ctx.registerSchema(schema)
   *   await registerAll(ctx)
   * }
   */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  registerSchema(schema: Record<string, any>): void
}

// ---------------------------------------------------------------------------
// Plugin manifest — static description of everything a plugin registers
// ---------------------------------------------------------------------------

export type SubcommandManifest = {
  name: string
  description: string
}

export type SubcommandGroupManifest = {
  name: string
  description: string
  subcommands: SubcommandManifest[]
}

export type CommandManifest = {
  name: string
  description?: string
  /** Direct `Subcommand` options (not inside a group) */
  subcommands: SubcommandManifest[]
  /** `SubcommandGroup` options, each containing their own subcommands */
  groups: SubcommandGroupManifest[]
}

export type ComponentManifest = {
  customId: string
  /** Values from `ResponderType`, e.g. `'button'`, `'modal'`, `'select.string'` */
  types: string[]
}

export type EventManifest = {
  name: string
  event: string
  once: boolean
}

export type CronManifest = {
  name: string
  cron: string
  once: boolean
}

/**
 * Side-effect-free snapshot of everything a plugin would register.
 * Produced by `Plugin.inspect()` without touching any global registry.
 */
export type PluginManifest = {
  metadata: PluginMetadata
  commands: CommandManifest[]
  components: ComponentManifest[]
  events: EventManifest[]
  configs: string[]
  crons: CronManifest[]
  /** Entity class names collected from `registerEntity` / `registerSchema` calls */
  entities: string[]
}

/**
 * Contract that every plugin module must satisfy.
 * Plugins are loaded via dynamic import(); this is what core expects to find.
 */
export interface PluginModule {
  /** Plugin metadata validated by core before setup() is called */
  metadata: PluginMetadata
  /** Called once by core to register commands, events, components, etc. */
  setup(ctx: PluginContext): Promise<void>
  /**
   * Returns a side-effect-free manifest of all registrations the plugin would
   * perform. Available when the plugin is defined with `new Plugin({...})`.
   */
  inspect?(): Promise<PluginManifest>
}
