/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSubscriptionRouteImport } from './routes/dashboard/subscription'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as AuthDiscordRouteImport } from './routes/auth.discord'
import { Route as DashboardReleasesIndexRouteImport } from './routes/dashboard/releases.index'
import { Route as DashboardPublisherIndexRouteImport } from './routes/dashboard/publisher.index'
import { Route as DashboardPluginsIndexRouteImport } from './routes/dashboard/plugins.index'
import { Route as DashboardNodesIndexRouteImport } from './routes/dashboard/nodes.index'
import { Route as DashboardMarketplaceIndexRouteImport } from './routes/dashboard/marketplace.index'
import { Route as DashboardBotsIndexRouteImport } from './routes/dashboard/bots.index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin.index'
import { Route as LoginDiscordCallbackRouteImport } from './routes/login.discord.callback'
import { Route as DashboardPublisherStatsRouteImport } from './routes/dashboard/publisher.stats'
import { Route as DashboardPluginsPluginIdRouteImport } from './routes/dashboard/plugins.$pluginId'
import { Route as DashboardNodesNodeIdRouteImport } from './routes/dashboard/nodes.$nodeId'
import { Route as DashboardBotsBotIdRouteImport } from './routes/dashboard/bots.$botId'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard/admin.users'
import { Route as DashboardAdminPluginRequestsRouteImport } from './routes/dashboard/admin.plugin-requests'
import { Route as DashboardBotsBotIdIndexRouteImport } from './routes/dashboard/bots.$botId.index'
import { Route as DashboardBotsBotIdPluginsRouteImport } from './routes/dashboard/bots.$botId.plugins'
import { Route as DashboardBotsBotIdLogsRouteImport } from './routes/dashboard/bots.$botId.logs'
import { Route as DashboardBotsBotIdDatabaseRouteImport } from './routes/dashboard/bots.$botId.database'
import { Route as DashboardBotsBotIdConfigRouteImport } from './routes/dashboard/bots.$botId.config'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSubscriptionRoute = DashboardSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthDiscordRoute = AuthDiscordRouteImport.update({
  id: '/auth/discord',
  path: '/auth/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReleasesIndexRoute = DashboardReleasesIndexRouteImport.update({
  id: '/releases/',
  path: '/releases/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPublisherIndexRoute = DashboardPublisherIndexRouteImport.update({
  id: '/publisher/',
  path: '/publisher/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPluginsIndexRoute = DashboardPluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNodesIndexRoute = DashboardNodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMarketplaceIndexRoute =
  DashboardMarketplaceIndexRouteImport.update({
    id: '/marketplace/',
    path: '/marketplace/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardBotsIndexRoute = DashboardBotsIndexRouteImport.update({
  id: '/bots/',
  path: '/bots/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const LoginDiscordCallbackRoute = LoginDiscordCallbackRouteImport.update({
  id: '/discord/callback',
  path: '/discord/callback',
  getParentRoute: () => LoginRoute,
} as any)
const DashboardPublisherStatsRoute = DashboardPublisherStatsRouteImport.update({
  id: '/publisher/stats',
  path: '/publisher/stats',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPluginsPluginIdRoute =
  DashboardPluginsPluginIdRouteImport.update({
    id: '/plugins/$pluginId',
    path: '/plugins/$pluginId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardNodesNodeIdRoute = DashboardNodesNodeIdRouteImport.update({
  id: '/nodes/$nodeId',
  path: '/nodes/$nodeId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBotsBotIdRoute = DashboardBotsBotIdRouteImport.update({
  id: '/bots/$botId',
  path: '/bots/$botId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminPluginRequestsRoute =
  DashboardAdminPluginRequestsRouteImport.update({
    id: '/admin/plugin-requests',
    path: '/admin/plugin-requests',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardBotsBotIdIndexRoute = DashboardBotsBotIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardBotsBotIdRoute,
} as any)
const DashboardBotsBotIdPluginsRoute =
  DashboardBotsBotIdPluginsRouteImport.update({
    id: '/plugins',
    path: '/plugins',
    getParentRoute: () => DashboardBotsBotIdRoute,
  } as any)
const DashboardBotsBotIdLogsRoute = DashboardBotsBotIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardBotsBotIdRoute,
} as any)
const DashboardBotsBotIdDatabaseRoute =
  DashboardBotsBotIdDatabaseRouteImport.update({
    id: '/database',
    path: '/database',
    getParentRoute: () => DashboardBotsBotIdRoute,
  } as any)
const DashboardBotsBotIdConfigRoute =
  DashboardBotsBotIdConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => DashboardBotsBotIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/auth/discord': typeof AuthDiscordRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/plugin-requests': typeof DashboardAdminPluginRequestsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/bots/$botId': typeof DashboardBotsBotIdRouteWithChildren
  '/dashboard/nodes/$nodeId': typeof DashboardNodesNodeIdRoute
  '/dashboard/plugins/$pluginId': typeof DashboardPluginsPluginIdRoute
  '/dashboard/publisher/stats': typeof DashboardPublisherStatsRoute
  '/login/discord/callback': typeof LoginDiscordCallbackRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/bots/': typeof DashboardBotsIndexRoute
  '/dashboard/marketplace/': typeof DashboardMarketplaceIndexRoute
  '/dashboard/nodes/': typeof DashboardNodesIndexRoute
  '/dashboard/plugins/': typeof DashboardPluginsIndexRoute
  '/dashboard/publisher/': typeof DashboardPublisherIndexRoute
  '/dashboard/releases/': typeof DashboardReleasesIndexRoute
  '/dashboard/bots/$botId/config': typeof DashboardBotsBotIdConfigRoute
  '/dashboard/bots/$botId/database': typeof DashboardBotsBotIdDatabaseRoute
  '/dashboard/bots/$botId/logs': typeof DashboardBotsBotIdLogsRoute
  '/dashboard/bots/$botId/plugins': typeof DashboardBotsBotIdPluginsRoute
  '/dashboard/bots/$botId/': typeof DashboardBotsBotIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/auth/discord': typeof AuthDiscordRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/plugin-requests': typeof DashboardAdminPluginRequestsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/nodes/$nodeId': typeof DashboardNodesNodeIdRoute
  '/dashboard/plugins/$pluginId': typeof DashboardPluginsPluginIdRoute
  '/dashboard/publisher/stats': typeof DashboardPublisherStatsRoute
  '/login/discord/callback': typeof LoginDiscordCallbackRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/bots': typeof DashboardBotsIndexRoute
  '/dashboard/marketplace': typeof DashboardMarketplaceIndexRoute
  '/dashboard/nodes': typeof DashboardNodesIndexRoute
  '/dashboard/plugins': typeof DashboardPluginsIndexRoute
  '/dashboard/publisher': typeof DashboardPublisherIndexRoute
  '/dashboard/releases': typeof DashboardReleasesIndexRoute
  '/dashboard/bots/$botId/config': typeof DashboardBotsBotIdConfigRoute
  '/dashboard/bots/$botId/database': typeof DashboardBotsBotIdDatabaseRoute
  '/dashboard/bots/$botId/logs': typeof DashboardBotsBotIdLogsRoute
  '/dashboard/bots/$botId/plugins': typeof DashboardBotsBotIdPluginsRoute
  '/dashboard/bots/$botId': typeof DashboardBotsBotIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/auth/discord': typeof AuthDiscordRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/plugin-requests': typeof DashboardAdminPluginRequestsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/bots/$botId': typeof DashboardBotsBotIdRouteWithChildren
  '/dashboard/nodes/$nodeId': typeof DashboardNodesNodeIdRoute
  '/dashboard/plugins/$pluginId': typeof DashboardPluginsPluginIdRoute
  '/dashboard/publisher/stats': typeof DashboardPublisherStatsRoute
  '/login/discord/callback': typeof LoginDiscordCallbackRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/bots/': typeof DashboardBotsIndexRoute
  '/dashboard/marketplace/': typeof DashboardMarketplaceIndexRoute
  '/dashboard/nodes/': typeof DashboardNodesIndexRoute
  '/dashboard/plugins/': typeof DashboardPluginsIndexRoute
  '/dashboard/publisher/': typeof DashboardPublisherIndexRoute
  '/dashboard/releases/': typeof DashboardReleasesIndexRoute
  '/dashboard/bots/$botId/config': typeof DashboardBotsBotIdConfigRoute
  '/dashboard/bots/$botId/database': typeof DashboardBotsBotIdDatabaseRoute
  '/dashboard/bots/$botId/logs': typeof DashboardBotsBotIdLogsRoute
  '/dashboard/bots/$botId/plugins': typeof DashboardBotsBotIdPluginsRoute
  '/dashboard/bots/$botId/': typeof DashboardBotsBotIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/auth/discord'
    | '/dashboard/settings'
    | '/dashboard/subscription'
    | '/dashboard/'
    | '/dashboard/admin/plugin-requests'
    | '/dashboard/admin/users'
    | '/dashboard/bots/$botId'
    | '/dashboard/nodes/$nodeId'
    | '/dashboard/plugins/$pluginId'
    | '/dashboard/publisher/stats'
    | '/login/discord/callback'
    | '/dashboard/admin/'
    | '/dashboard/bots/'
    | '/dashboard/marketplace/'
    | '/dashboard/nodes/'
    | '/dashboard/plugins/'
    | '/dashboard/publisher/'
    | '/dashboard/releases/'
    | '/dashboard/bots/$botId/config'
    | '/dashboard/bots/$botId/database'
    | '/dashboard/bots/$botId/logs'
    | '/dashboard/bots/$botId/plugins'
    | '/dashboard/bots/$botId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auth/discord'
    | '/dashboard/settings'
    | '/dashboard/subscription'
    | '/dashboard'
    | '/dashboard/admin/plugin-requests'
    | '/dashboard/admin/users'
    | '/dashboard/nodes/$nodeId'
    | '/dashboard/plugins/$pluginId'
    | '/dashboard/publisher/stats'
    | '/login/discord/callback'
    | '/dashboard/admin'
    | '/dashboard/bots'
    | '/dashboard/marketplace'
    | '/dashboard/nodes'
    | '/dashboard/plugins'
    | '/dashboard/publisher'
    | '/dashboard/releases'
    | '/dashboard/bots/$botId/config'
    | '/dashboard/bots/$botId/database'
    | '/dashboard/bots/$botId/logs'
    | '/dashboard/bots/$botId/plugins'
    | '/dashboard/bots/$botId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/auth/discord'
    | '/dashboard/settings'
    | '/dashboard/subscription'
    | '/dashboard/'
    | '/dashboard/admin/plugin-requests'
    | '/dashboard/admin/users'
    | '/dashboard/bots/$botId'
    | '/dashboard/nodes/$nodeId'
    | '/dashboard/plugins/$pluginId'
    | '/dashboard/publisher/stats'
    | '/login/discord/callback'
    | '/dashboard/admin/'
    | '/dashboard/bots/'
    | '/dashboard/marketplace/'
    | '/dashboard/nodes/'
    | '/dashboard/plugins/'
    | '/dashboard/publisher/'
    | '/dashboard/releases/'
    | '/dashboard/bots/$botId/config'
    | '/dashboard/bots/$botId/database'
    | '/dashboard/bots/$botId/logs'
    | '/dashboard/bots/$botId/plugins'
    | '/dashboard/bots/$botId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  AuthDiscordRoute: typeof AuthDiscordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/subscription': {
      id: '/dashboard/subscription'
      path: '/subscription'
      fullPath: '/dashboard/subscription'
      preLoaderRoute: typeof DashboardSubscriptionRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/discord': {
      id: '/auth/discord'
      path: '/auth/discord'
      fullPath: '/auth/discord'
      preLoaderRoute: typeof AuthDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/releases/': {
      id: '/dashboard/releases/'
      path: '/releases'
      fullPath: '/dashboard/releases/'
      preLoaderRoute: typeof DashboardReleasesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/publisher/': {
      id: '/dashboard/publisher/'
      path: '/publisher'
      fullPath: '/dashboard/publisher/'
      preLoaderRoute: typeof DashboardPublisherIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/plugins/': {
      id: '/dashboard/plugins/'
      path: '/plugins'
      fullPath: '/dashboard/plugins/'
      preLoaderRoute: typeof DashboardPluginsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/nodes/': {
      id: '/dashboard/nodes/'
      path: '/nodes'
      fullPath: '/dashboard/nodes/'
      preLoaderRoute: typeof DashboardNodesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/marketplace/': {
      id: '/dashboard/marketplace/'
      path: '/marketplace'
      fullPath: '/dashboard/marketplace/'
      preLoaderRoute: typeof DashboardMarketplaceIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/bots/': {
      id: '/dashboard/bots/'
      path: '/bots'
      fullPath: '/dashboard/bots/'
      preLoaderRoute: typeof DashboardBotsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/admin'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/login/discord/callback': {
      id: '/login/discord/callback'
      path: '/discord/callback'
      fullPath: '/login/discord/callback'
      preLoaderRoute: typeof LoginDiscordCallbackRouteImport
      parentRoute: typeof LoginRoute
    }
    '/dashboard/publisher/stats': {
      id: '/dashboard/publisher/stats'
      path: '/publisher/stats'
      fullPath: '/dashboard/publisher/stats'
      preLoaderRoute: typeof DashboardPublisherStatsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/plugins/$pluginId': {
      id: '/dashboard/plugins/$pluginId'
      path: '/plugins/$pluginId'
      fullPath: '/dashboard/plugins/$pluginId'
      preLoaderRoute: typeof DashboardPluginsPluginIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/nodes/$nodeId': {
      id: '/dashboard/nodes/$nodeId'
      path: '/nodes/$nodeId'
      fullPath: '/dashboard/nodes/$nodeId'
      preLoaderRoute: typeof DashboardNodesNodeIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/bots/$botId': {
      id: '/dashboard/bots/$botId'
      path: '/bots/$botId'
      fullPath: '/dashboard/bots/$botId'
      preLoaderRoute: typeof DashboardBotsBotIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin/plugin-requests': {
      id: '/dashboard/admin/plugin-requests'
      path: '/admin/plugin-requests'
      fullPath: '/dashboard/admin/plugin-requests'
      preLoaderRoute: typeof DashboardAdminPluginRequestsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/bots/$botId/': {
      id: '/dashboard/bots/$botId/'
      path: '/'
      fullPath: '/dashboard/bots/$botId/'
      preLoaderRoute: typeof DashboardBotsBotIdIndexRouteImport
      parentRoute: typeof DashboardBotsBotIdRoute
    }
    '/dashboard/bots/$botId/plugins': {
      id: '/dashboard/bots/$botId/plugins'
      path: '/plugins'
      fullPath: '/dashboard/bots/$botId/plugins'
      preLoaderRoute: typeof DashboardBotsBotIdPluginsRouteImport
      parentRoute: typeof DashboardBotsBotIdRoute
    }
    '/dashboard/bots/$botId/logs': {
      id: '/dashboard/bots/$botId/logs'
      path: '/logs'
      fullPath: '/dashboard/bots/$botId/logs'
      preLoaderRoute: typeof DashboardBotsBotIdLogsRouteImport
      parentRoute: typeof DashboardBotsBotIdRoute
    }
    '/dashboard/bots/$botId/database': {
      id: '/dashboard/bots/$botId/database'
      path: '/database'
      fullPath: '/dashboard/bots/$botId/database'
      preLoaderRoute: typeof DashboardBotsBotIdDatabaseRouteImport
      parentRoute: typeof DashboardBotsBotIdRoute
    }
    '/dashboard/bots/$botId/config': {
      id: '/dashboard/bots/$botId/config'
      path: '/config'
      fullPath: '/dashboard/bots/$botId/config'
      preLoaderRoute: typeof DashboardBotsBotIdConfigRouteImport
      parentRoute: typeof DashboardBotsBotIdRoute
    }
  }
}

interface DashboardBotsBotIdRouteChildren {
  DashboardBotsBotIdConfigRoute: typeof DashboardBotsBotIdConfigRoute
  DashboardBotsBotIdDatabaseRoute: typeof DashboardBotsBotIdDatabaseRoute
  DashboardBotsBotIdLogsRoute: typeof DashboardBotsBotIdLogsRoute
  DashboardBotsBotIdPluginsRoute: typeof DashboardBotsBotIdPluginsRoute
  DashboardBotsBotIdIndexRoute: typeof DashboardBotsBotIdIndexRoute
}

const DashboardBotsBotIdRouteChildren: DashboardBotsBotIdRouteChildren = {
  DashboardBotsBotIdConfigRoute: DashboardBotsBotIdConfigRoute,
  DashboardBotsBotIdDatabaseRoute: DashboardBotsBotIdDatabaseRoute,
  DashboardBotsBotIdLogsRoute: DashboardBotsBotIdLogsRoute,
  DashboardBotsBotIdPluginsRoute: DashboardBotsBotIdPluginsRoute,
  DashboardBotsBotIdIndexRoute: DashboardBotsBotIdIndexRoute,
}

const DashboardBotsBotIdRouteWithChildren =
  DashboardBotsBotIdRoute._addFileChildren(DashboardBotsBotIdRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSubscriptionRoute: typeof DashboardSubscriptionRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminPluginRequestsRoute: typeof DashboardAdminPluginRequestsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardBotsBotIdRoute: typeof DashboardBotsBotIdRouteWithChildren
  DashboardNodesNodeIdRoute: typeof DashboardNodesNodeIdRoute
  DashboardPluginsPluginIdRoute: typeof DashboardPluginsPluginIdRoute
  DashboardPublisherStatsRoute: typeof DashboardPublisherStatsRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardBotsIndexRoute: typeof DashboardBotsIndexRoute
  DashboardMarketplaceIndexRoute: typeof DashboardMarketplaceIndexRoute
  DashboardNodesIndexRoute: typeof DashboardNodesIndexRoute
  DashboardPluginsIndexRoute: typeof DashboardPluginsIndexRoute
  DashboardPublisherIndexRoute: typeof DashboardPublisherIndexRoute
  DashboardReleasesIndexRoute: typeof DashboardReleasesIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSubscriptionRoute: DashboardSubscriptionRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminPluginRequestsRoute: DashboardAdminPluginRequestsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardBotsBotIdRoute: DashboardBotsBotIdRouteWithChildren,
  DashboardNodesNodeIdRoute: DashboardNodesNodeIdRoute,
  DashboardPluginsPluginIdRoute: DashboardPluginsPluginIdRoute,
  DashboardPublisherStatsRoute: DashboardPublisherStatsRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardBotsIndexRoute: DashboardBotsIndexRoute,
  DashboardMarketplaceIndexRoute: DashboardMarketplaceIndexRoute,
  DashboardNodesIndexRoute: DashboardNodesIndexRoute,
  DashboardPluginsIndexRoute: DashboardPluginsIndexRoute,
  DashboardPublisherIndexRoute: DashboardPublisherIndexRoute,
  DashboardReleasesIndexRoute: DashboardReleasesIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface LoginRouteChildren {
  LoginDiscordCallbackRoute: typeof LoginDiscordCallbackRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginDiscordCallbackRoute: LoginDiscordCallbackRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  AuthDiscordRoute: AuthDiscordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
