/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPluginsRouteImport } from './routes/_authenticated/plugins'
import { Route as AuthenticatedDownloadsRouteImport } from './routes/_authenticated/downloads'
import { Route as AuthenticatedBotsRouteImport } from './routes/_authenticated/bots'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as LoginDiscordCallbackRouteImport } from './routes/login.discord.callback'
import { Route as AuthenticatedBotsBotIdRouteImport } from './routes/_authenticated/bots_.$botId'
import { Route as AuthenticatedBotsBotIdIndexRouteImport } from './routes/_authenticated/bots_.$botId.index'
import { Route as AuthenticatedBotsBotIdPluginsRouteImport } from './routes/_authenticated/bots_.$botId.plugins'
import { Route as AuthenticatedBotsBotIdLogsRouteImport } from './routes/_authenticated/bots_.$botId.logs'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPluginsRoute = AuthenticatedPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDownloadsRoute = AuthenticatedDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBotsRoute = AuthenticatedBotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LoginDiscordCallbackRoute = LoginDiscordCallbackRouteImport.update({
  id: '/discord/callback',
  path: '/discord/callback',
  getParentRoute: () => LoginRoute,
} as any)
const AuthenticatedBotsBotIdRoute = AuthenticatedBotsBotIdRouteImport.update({
  id: '/bots_/$botId',
  path: '/bots/$botId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBotsBotIdIndexRoute =
  AuthenticatedBotsBotIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBotsBotIdRoute,
  } as any)
const AuthenticatedBotsBotIdPluginsRoute =
  AuthenticatedBotsBotIdPluginsRouteImport.update({
    id: '/plugins',
    path: '/plugins',
    getParentRoute: () => AuthenticatedBotsBotIdRoute,
  } as any)
const AuthenticatedBotsBotIdLogsRoute =
  AuthenticatedBotsBotIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedBotsBotIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/bots': typeof AuthenticatedBotsRoute
  '/downloads': typeof AuthenticatedDownloadsRoute
  '/plugins': typeof AuthenticatedPluginsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/login/': typeof LoginIndexRoute
  '/bots/$botId': typeof AuthenticatedBotsBotIdRouteWithChildren
  '/login/discord/callback': typeof LoginDiscordCallbackRoute
  '/bots/$botId/logs': typeof AuthenticatedBotsBotIdLogsRoute
  '/bots/$botId/plugins': typeof AuthenticatedBotsBotIdPluginsRoute
  '/bots/$botId/': typeof AuthenticatedBotsBotIdIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AuthenticatedAdminRoute
  '/bots': typeof AuthenticatedBotsRoute
  '/downloads': typeof AuthenticatedDownloadsRoute
  '/plugins': typeof AuthenticatedPluginsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginIndexRoute
  '/login/discord/callback': typeof LoginDiscordCallbackRoute
  '/bots/$botId/logs': typeof AuthenticatedBotsBotIdLogsRoute
  '/bots/$botId/plugins': typeof AuthenticatedBotsBotIdPluginsRoute
  '/bots/$botId': typeof AuthenticatedBotsBotIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bots': typeof AuthenticatedBotsRoute
  '/_authenticated/downloads': typeof AuthenticatedDownloadsRoute
  '/_authenticated/plugins': typeof AuthenticatedPluginsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/bots_/$botId': typeof AuthenticatedBotsBotIdRouteWithChildren
  '/login/discord/callback': typeof LoginDiscordCallbackRoute
  '/_authenticated/bots_/$botId/logs': typeof AuthenticatedBotsBotIdLogsRoute
  '/_authenticated/bots_/$botId/plugins': typeof AuthenticatedBotsBotIdPluginsRoute
  '/_authenticated/bots_/$botId/': typeof AuthenticatedBotsBotIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/bots'
    | '/downloads'
    | '/plugins'
    | '/settings'
    | '/users'
    | '/login/'
    | '/bots/$botId'
    | '/login/discord/callback'
    | '/bots/$botId/logs'
    | '/bots/$botId/plugins'
    | '/bots/$botId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/bots'
    | '/downloads'
    | '/plugins'
    | '/settings'
    | '/users'
    | '/'
    | '/login'
    | '/login/discord/callback'
    | '/bots/$botId/logs'
    | '/bots/$botId/plugins'
    | '/bots/$botId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/bots'
    | '/_authenticated/downloads'
    | '/_authenticated/plugins'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/login/'
    | '/_authenticated/bots_/$botId'
    | '/login/discord/callback'
    | '/_authenticated/bots_/$botId/logs'
    | '/_authenticated/bots_/$botId/plugins'
    | '/_authenticated/bots_/$botId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plugins': {
      id: '/_authenticated/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof AuthenticatedPluginsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/downloads': {
      id: '/_authenticated/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AuthenticatedDownloadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bots': {
      id: '/_authenticated/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof AuthenticatedBotsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/login/discord/callback': {
      id: '/login/discord/callback'
      path: '/discord/callback'
      fullPath: '/login/discord/callback'
      preLoaderRoute: typeof LoginDiscordCallbackRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_authenticated/bots_/$botId': {
      id: '/_authenticated/bots_/$botId'
      path: '/bots/$botId'
      fullPath: '/bots/$botId'
      preLoaderRoute: typeof AuthenticatedBotsBotIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bots_/$botId/': {
      id: '/_authenticated/bots_/$botId/'
      path: '/'
      fullPath: '/bots/$botId/'
      preLoaderRoute: typeof AuthenticatedBotsBotIdIndexRouteImport
      parentRoute: typeof AuthenticatedBotsBotIdRoute
    }
    '/_authenticated/bots_/$botId/plugins': {
      id: '/_authenticated/bots_/$botId/plugins'
      path: '/plugins'
      fullPath: '/bots/$botId/plugins'
      preLoaderRoute: typeof AuthenticatedBotsBotIdPluginsRouteImport
      parentRoute: typeof AuthenticatedBotsBotIdRoute
    }
    '/_authenticated/bots_/$botId/logs': {
      id: '/_authenticated/bots_/$botId/logs'
      path: '/logs'
      fullPath: '/bots/$botId/logs'
      preLoaderRoute: typeof AuthenticatedBotsBotIdLogsRouteImport
      parentRoute: typeof AuthenticatedBotsBotIdRoute
    }
  }
}

interface AuthenticatedBotsBotIdRouteChildren {
  AuthenticatedBotsBotIdLogsRoute: typeof AuthenticatedBotsBotIdLogsRoute
  AuthenticatedBotsBotIdPluginsRoute: typeof AuthenticatedBotsBotIdPluginsRoute
  AuthenticatedBotsBotIdIndexRoute: typeof AuthenticatedBotsBotIdIndexRoute
}

const AuthenticatedBotsBotIdRouteChildren: AuthenticatedBotsBotIdRouteChildren =
  {
    AuthenticatedBotsBotIdLogsRoute: AuthenticatedBotsBotIdLogsRoute,
    AuthenticatedBotsBotIdPluginsRoute: AuthenticatedBotsBotIdPluginsRoute,
    AuthenticatedBotsBotIdIndexRoute: AuthenticatedBotsBotIdIndexRoute,
  }

const AuthenticatedBotsBotIdRouteWithChildren =
  AuthenticatedBotsBotIdRoute._addFileChildren(
    AuthenticatedBotsBotIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBotsRoute: typeof AuthenticatedBotsRoute
  AuthenticatedDownloadsRoute: typeof AuthenticatedDownloadsRoute
  AuthenticatedPluginsRoute: typeof AuthenticatedPluginsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBotsBotIdRoute: typeof AuthenticatedBotsBotIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBotsRoute: AuthenticatedBotsRoute,
  AuthenticatedDownloadsRoute: AuthenticatedDownloadsRoute,
  AuthenticatedPluginsRoute: AuthenticatedPluginsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBotsBotIdRoute: AuthenticatedBotsBotIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface LoginRouteChildren {
  LoginIndexRoute: typeof LoginIndexRoute
  LoginDiscordCallbackRoute: typeof LoginDiscordCallbackRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginIndexRoute: LoginIndexRoute,
  LoginDiscordCallbackRoute: LoginDiscordCallbackRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
