name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  prepare:
    name: Prepare job
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Pre-build
        run: PREBUILD=true bun run build

      - uses: actions/upload-artifact@v4
        name: Upload pre-build artifact
        with:
          name: pre-build
          path: ./releases

  build_multi_linux:
    name: Build Linux ${{ matrix.arch }}
    needs: prepare
    runs-on: ${{ matrix.distro }}
    strategy:
      matrix:
        include:
          - distro: ubuntu-22.04
            arch: aarch64
          - distro: ubuntu-22.04
            arch: x64
      max-parallel: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download pre-build artifact (aarch64 only)
        if: matrix.arch == 'aarch64'
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ github.token }}
          name: pre-build
          path: ./releases

      - name: Download aarch64 artifact (x64 only)
        if: matrix.arch == 'x64'
        uses: actions/download-artifact@v4
        with:
          name: build-ubuntu-latest-aarch64
          path: ./releases

      - uses: uraimo/run-on-arch-action@v2
        name: Build artifact ${{ matrix.arch }}
        if: matrix.arch == 'aarch64'
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu22.04
          githubToken: ${{ github.token }}
          install: |
            apt update && apt upgrade -y && apt install -y curl unzip ca-certificates curl gnupg
            curl -fsSL https://bun.sh/install | bash
          run: |
            export BUN_INSTALL="$HOME/.bun"
            export PATH="$BUN_INSTALL/bin:$PATH"
            bun install
            BINARY=true bun run build

      - uses: oven-sh/setup-bun@v2
        if: matrix.arch == 'x64'
        with:
          bun-version: latest

      - name: Rebuild Modules (x64 only)
        if: matrix.arch == 'x64'
        run: rm -rf node_modules && bun install

      - name: Build Release
        if: matrix.arch == 'x64'
        run: BINARY=true bun run build

      - uses: actions/upload-artifact@v4
        name: Upload build artifact
        with:
          name: build-ubuntu-latest-${{ matrix.arch }}
          path: ./releases

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: releases/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

  build_windows:
    name: Build Windows
    needs: prepare
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build Windows Executable
        run: set BINARY=true && bun run build

      - uses: actions/upload-artifact@v4
        name: Upload Windows Artifact
        with:
          name: windows-build
          path: ./releases

      - name: Upload Windows EXE to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: releases/*.exe
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true